### ISSUE TITLE
一部レイアウトに崩れるところあり

### ISSUE THREAD

**Issue by taichanNE30** [ne-v-project2020/recruitment-web#10]
iPhone
![IMG_8144](https://user-images.githubusercontent.com/40626578/69812933-852ade80-1234-11ea-8c2e-8786e23db73f.PNG)

iPad
![IMG_0055](https://user-images.githubusercontent.com/40626578/69812949-8fe57380-1234-11ea-911a-8fbec39236c0.PNG)

Softの部分が表示されない

<img width="848" alt="スクリーンショット 2019-11-28 23 13 21" src="https://user-images.githubusercontent.com/40626578/69813039-befbe500-1234-11ea-8b47-211efc53bc25.png">

PCのFirefoxでも幅小さくしたらなったのでCSSの問題っぽい？

**Comment by H0L1C** [comment]
あー完璧に理解した
多分すぐ修正できるのでローディングアニメーションのブランチマージしたあとに別のブランチ切って修正するので大丈夫？

**Comment by taichanNE30** [comment]
急ぎじゃないので明日でもOK

**Comment by H0L1C** [comment]
大体直したので寝る前にプルリクだけします
