### ISSUE TITLE
OGP設定

### ISSUE THREAD

**Issue by H0L1C** [ne-v-project2020/recruitment-web#23]

**Comment by taichanNE30** [comment]
これもう閉じていいやつかな

**Comment by H0L1C** [comment]
せやね
閉じます

**Comment by taichanNE30** [comment]
<img width="626" alt="スクリーンショット 2019-12-11 0 35 05" src="https://user-images.githubusercontent.com/40626578/70543693-23606200-1bae-11ea-8d12-422889e2f8b0.png">
